// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnufjxloqatnyyguwmdi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudWZqeGxvcWF0bnl5Z3V3bWRpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MDcwNzQsImV4cCI6MjA1NzI4MzA3NH0.96iKRULxz0NrRxwGPzbi6sxHljAvgQECmfCUrLe7dpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);